reclamos2/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  root :to=>  'inicio#index'
  get 'inicio/index'
  resources :reclamos
  resources :clientes
end

reclamos2/app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

reclamos2/app/models/reclamo.rb
class Reclamo < ActiveRecord::Base
  belongs_to :rut_cliente
end

reclamos2/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

reclamos2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

reclamos2/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:rut_cliente, :nombre_cliente, :fono_cliente, :email)
    end
end

reclamos2/app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

reclamos2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_usuario!, except: [:show, :index]

    #GET /posts
    #GET /posts.json

reclamos2/app/controllers/reclamos_controller.rb
class ReclamosController < ApplicationController
  before_action :set_reclamo, only: [:show, :edit, :update, :destroy]

  # GET /reclamos
  # GET /reclamos.json
  def index
    @reclamos = Reclamo.all
  end

  # GET /reclamos/1
  # GET /reclamos/1.json
  def show
  end

  # GET /reclamos/new
  def new
    @reclamo = Reclamo.new
  end

  # GET /reclamos/1/edit
  def edit
  end

  # POST /reclamos
  # POST /reclamos.json
  def create
    @reclamo = Reclamo.new(reclamo_params)

    respond_to do |format|
      if @reclamo.save
        format.html { redirect_to @reclamo, notice: 'Reclamo was successfully created.' }
        format.json { render :show, status: :created, location: @reclamo }
      else
        format.html { render :new }
        format.json { render json: @reclamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclamos/1
  # PATCH/PUT /reclamos/1.json
  def update
    respond_to do |format|
      if @reclamo.update(reclamo_params)
        format.html { redirect_to @reclamo, notice: 'Reclamo was successfully updated.' }
        format.json { render :show, status: :ok, location: @reclamo }
      else
        format.html { render :edit }
        format.json { render json: @reclamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamos/1
  # DELETE /reclamos/1.json
  def destroy
    @reclamo.destroy
    respond_to do |format|
      format.html { redirect_to reclamos_url, notice: 'Reclamo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reclamo
      @reclamo = Reclamo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reclamo_params
      params.require(:reclamo).permit(:empresa, :reclamo, :rut_cliente_id, :cliente)
    end
end

reclamos2/app/helpers/application_helper.rb
module ApplicationHelper
end

reclamos2/app/helpers/clientes_helper.rb
module ClientesHelper
end

reclamos2/app/helpers/inicio_helper.rb
module InicioHelper
end

reclamos2/app/helpers/reclamos_helper.rb
module ReclamosHelper
end

reclamos2/app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rut_cliente %><br>
    <%= f.text_field :rut_cliente %>
  </div>
  <div class="field">
    <%= f.label :nombre_cliente %><br>
    <%= f.text_field :nombre_cliente %>
  </div>
  <div class="field">
    <%= f.label :fono_cliente %><br>
    <%= f.number_field :fono_cliente %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reclamos2/app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

reclamos2/app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <thead>
    <tr>
      <th>Rut cliente</th>
      <th>Nombre cliente</th>
      <th>Fono cliente</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.rut_cliente %></td>
        <td><%= cliente.nombre_cliente %></td>
        <td><%= cliente.fono_cliente %></td>
        <td><%= cliente.email %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

reclamos2/app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

reclamos2/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut cliente:</strong>
  <%= @cliente.rut_cliente %>
</p>

<p>
  <strong>Nombre cliente:</strong>
  <%= @cliente.nombre_cliente %>
</p>

<p>
  <strong>Fono cliente:</strong>
  <%= @cliente.fono_cliente %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

reclamos2/app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>
<p><%= link_to 'Clientes', clientes_path %></p>
<p><%= link_to 'Reclamos', reclamos_path %></p>

reclamos2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reclamos2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'shared/navbar' %>
<div class="container">
  <%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>  
</div>
</body>
</html>

reclamos2/app/views/reclamos/_form.html.erb
<%= form_for(@reclamo) do |f| %>
  <% if @reclamo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reclamo.errors.count, "error") %> prohibited this reclamo from being saved:</h2>

      <ul>
      <% @reclamo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :empresa %><br>
    <%= f.text_field :empresa %>
  </div>
  <div class="field">
    <%= f.label :reclamo %><br>
    <%= f.text_field :reclamo %>
  </div>
  <div class="field">
    <%= f.label :rut_cliente_id %><br>
    <%= f.text_field :rut_cliente_id %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reclamos2/app/views/reclamos/edit.html.erb
<h1>Editing reclamo</h1>

<%= render 'form' %>

<%= link_to 'Show', @reclamo %> |
<%= link_to 'Back', reclamos_path %>

reclamos2/app/views/reclamos/index.html.erb
<h1>Listing reclamos</h1>

<table>
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Reclamo</th>
      <th>Rut cliente</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamos.each do |reclamo| %>
      <tr>
        <td><%= reclamo.empresa %></td>
        <td><%= reclamo.reclamo %></td>
        <td><%= reclamo.rut_cliente %></td>
        <td><%= reclamo.cliente %></td>
        <td><%= link_to 'Show', reclamo %></td>
        <td><%= link_to 'Edit', edit_reclamo_path(reclamo) %></td>
        <td><%= link_to 'Destroy', reclamo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reclamo', new_reclamo_path %>

reclamos2/app/views/reclamos/new.html.erb
<h1>New reclamo</h1>

<%= render 'form' %>

<%= link_to 'Back', reclamos_path %>

reclamos2/app/views/reclamos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @reclamo.empresa %>
</p>

<p>
  <strong>Reclamo:</strong>
  <%= @reclamo.reclamo %>
</p>

<p>
  <strong>Rut cliente:</strong>
  <%= @reclamo.rut_cliente %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @reclamo.cliente %>
</p>

<%= link_to 'Edit', edit_reclamo_path(@reclamo) %> |
<%= link_to 'Back', reclamos_path %>